# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 生命不息 代码不止 # ex. I m Chuan
name: 禅心诡道 # ex. DONGChuan
email: 693196756@qq.com
location: FuJian # ex. Nice, France
company: 每一份教程，我都会亲手敲一遍，如果你学习过程遇到问题，欢迎留言(点我查看技能树)。
company_url: https://www.processon.com/view/5c89f14ae4b0f88919ad93e1#map
github_url: https://github.com/chanxinguidao # ex. https://github.com/DONGChuan
github_username: # ex. DONGChuan
subTitle: 我们熟悉的甲骨文在北京裁员了!而你还不认真学习！
subTitle_url: https://mp.weixin.qq.com/s/J5IMG0P4PKpUTofCTuZlgA
description: 而立之年，方知代码才是真爱
favicon: favicon.png # Image must be in assets/images
repository: github.com/chanxinguidao/chanxinguidao.github.com # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://chanxinguidao.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /java-base.html
    label: Java
    target: _self
    subnav:

      -
        subHref: /java-base.html
        subLabel: Java基础
      -
        subHref: /java-thread.html
        subLabel: Java线程


  -
    href: /spring-boot.html
    label: Spring
    target: _self
    subnav:


      -
        subHref: /spring-boot.html
        subLabel: Spring Boot

      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud

  -
    href: /archives.html
    label: Archives
    target: _self
  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: chanxinguidao
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: chanxinguidao
  repo: chanxinguidao.github.com
  oauth:
    client_id: d67652d2c49c7958abb4
    client_secret: 93b0961a0a6a6b50b5f1cd7b1c6e56f971098c68
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: chanxinguidao
  repo: chanxinguidao.github.com
  clientID: d67652d2c49c7958abb4
  clientSecret: 93b0961a0a6a6b50b5f1cd7b1c6e56f971098c68
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
comments:
  gitalk: true
  gitalk_clientID: d67652d2c49c7958abb4
  gitalk_Secret: 93b0961a0a6a6b50b5f1cd7b1c6e56f971098c68
  gitalk_repo: chanxinguidao.github.com
  gitalk_owner: chanxinguidao
  gitalk_admin: chanxinguidao
  distractionFreeMode: true
